spring:
  datasource:
    url: jdbc://postgresql://localhost:5432/bookglobal
    username: sysbookglobal
    password: cac1ef4af1ad9fe795431d3924893733
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSLDialect
  mail:
    host: localhost
    port: 1025
    username: javier
    password: villalobos
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000